name: udder-app
services:
  - name: api
    github:
      branch: master
      deploy_on_push: true
      repo: rlmsinclair/udder-app
    source_dir: /
    envs:
      - key: XAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /
    health_check:
      http_path: /heartbeat
    build_command: pip install -r requirements.txt
    packages:
      - ffmpeg
      - python3-dev
      - build-essential
