name: udder
services:
  - name: web
    git:
      branch: master
      repo_clone_url: ${REPO_URL}
    buildpacks:
      - name: digitalocean/custom
      - name: heroku/python
    build_command: |
      apt-get update
      apt-get install -y ffmpeg libavcodec-extra libavformat-dev libavutil-dev
      pip install -r requirements.txt
    run_command: uvicorn app:app --host 0.0.0.0 --port $PORT
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        value: ${OPENAI_API_KEY}
      - key: GEMINI_API_KEY
        scope: RUN_TIME
        value: ${GEMINI_API_KEY}
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    http_port: 8080
