name: udder-app
services:
  - name: api
    github:
      branch: main
      deploy_on_push: true
      repo: rlmsinclair/udder-app
    source_dir: /
    dockerfile_path: Dockerfile
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: FFMPEG_PATH
        scope: RUN_TIME
        value: /usr/bin/ffmpeg
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    routes:
      - path: /
    health_check:
      http_path: /heartbeat
    run_command: python server.py
    packages:
      - ffmpeg
